#!/usr/bin/env bash
#
# Drop any image into content/images/ and run this script.
# It generates three web-sized derivatives (thumb / preview / detail)
# and rewrites js/fine-art-manifest.js so the site picks up new pieces
# automatically — no manual file-system.js editing.
#
# Usage:
#   ./scripts/process-images.sh
#
# Requires: macOS `sips` (built in). No npm / brew install needed.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC_DIR="$ROOT/content/images"
WEB_DIR="$SRC_DIR/web"
MANIFEST="$ROOT/js/fine-art-manifest.js"

THUMB_PX=300
PREVIEW_PX=1200
DETAIL_PX=4000

mkdir -p "$WEB_DIR/thumb" "$WEB_DIR/preview"

# Sanitize filename → URL-safe slug (no spaces, no special chars).
slugify() {
  printf "%s" "$1" \
    | sed -E 's/\.[^.]+$//' \
    | tr '[:upper:]' '[:lower:]' \
    | tr -cs 'a-z0-9' '-' \
    | sed -E 's/^-+|-+$//g'
}

# `find` (POSIX) handles spaces, unlike a naive glob.
masters=()
while IFS= read -r -d '' f; do
  masters+=("$f")
done < <(find "$SRC_DIR" -maxdepth 1 -type f \
  \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \
     -o -iname '*.tif' -o -iname '*.tiff' \) -print0)

if [ "${#masters[@]}" -eq 0 ]; then
  echo "No master images found in $SRC_DIR — nothing to do."
  # Still write an empty manifest so the site code doesn't break.
  printf '%s\n' \
    "// AUTO-GENERATED by scripts/process-images.sh — do not edit by hand." \
    "export const FINE_ART = [];" > "$MANIFEST"
  exit 0
fi

# Sort masters by mtime so the manifest order is stable + newest-first.
sorted_masters=()
while IFS= read -r -d '' line; do
  sorted_masters+=("${line#*	}")
done < <(printf '%s\0' "${masters[@]}" \
  | xargs -0 stat -f '%m	%N' \
  | sort -rn -t '	' -k1 \
  | tr '\n' '\0')

# Build manifest as we go.
entries=""
for src in "${sorted_masters[@]}"; do
  filename="$(basename "$src")"
  slug="$(slugify "$filename")"
  if [ -z "$slug" ]; then
    echo "Skipping (could not slugify): $filename"
    continue
  fi

  thumb_out="$WEB_DIR/thumb/${slug}.jpg"
  preview_out="$WEB_DIR/preview/${slug}.jpg"
  detail_out="$WEB_DIR/${slug}.jpg"

  # Skip if derivatives are newer than the source (idempotent re-runs).
  needs_thumb=1;   [ -e "$thumb_out"   ] && [ "$thumb_out"   -nt "$src" ] && needs_thumb=0
  needs_preview=1; [ -e "$preview_out" ] && [ "$preview_out" -nt "$src" ] && needs_preview=0
  needs_detail=1;  [ -e "$detail_out"  ] && [ "$detail_out"  -nt "$src" ] && needs_detail=0

  if [ "$needs_thumb" = "1" ] || [ "$needs_preview" = "1" ] || [ "$needs_detail" = "1" ]; then
    echo "Processing: $filename → ${slug}.jpg"
    [ "$needs_thumb"   = "1" ] && sips -Z $THUMB_PX   "$src" --out "$thumb_out"   -s format jpeg -s formatOptions 80 >/dev/null
    [ "$needs_preview" = "1" ] && sips -Z $PREVIEW_PX "$src" --out "$preview_out" -s format jpeg -s formatOptions 82 >/dev/null
    [ "$needs_detail"  = "1" ] && sips -Z $DETAIL_PX  "$src" --out "$detail_out"  -s format jpeg -s formatOptions 90 >/dev/null
  else
    echo "Up to date: ${slug}.jpg"
  fi

  # Read the detail's final dimensions so the viewer can show the master
  # size regardless of which progressive level is currently displayed.
  detail_w=$(sips -g pixelWidth  "$detail_out" 2>/dev/null | tail -n1 | awk '{print $NF}')
  detail_h=$(sips -g pixelHeight "$detail_out" 2>/dev/null | tail -n1 | awk '{print $NF}')

  # Display name = filename minus its extension (so "Goddess of Memory.png"
  # shows as "Goddess of Memory" in the UI, while we still know the source
  # filename via `name`).
  displayName="${filename%.*}"

  entries+="  {\n"
  entries+="    name: \"${displayName}\",\n"
  entries+="    type: \"file\",\n"
  entries+="    kind: \"image\",\n"
  entries+="    thumb:    \"content/images/web/thumb/${slug}.jpg\",\n"
  entries+="    preview:  \"content/images/web/preview/${slug}.jpg\",\n"
  entries+="    src:      \"content/images/web/${slug}.jpg\",\n"
  entries+="    detailW:  ${detail_w:-0},\n"
  entries+="    detailH:  ${detail_h:-0},\n"
  entries+="  },\n"
done

# Prune orphan derivatives — files in web/ that no longer have a master.
expected_slugs=""
for src in "${sorted_masters[@]}"; do
  expected_slugs+=" $(slugify "$(basename "$src")")"
done
for f in "$WEB_DIR"/*.jpg "$WEB_DIR"/thumb/*.jpg "$WEB_DIR"/preview/*.jpg; do
  [ -e "$f" ] || continue
  name="$(basename "$f" .jpg)"
  case " $expected_slugs " in
    *" $name "*) ;;     # still wanted
    *) echo "Pruning orphan: $f"; rm -f "$f" ;;
  esac
done

# Write the manifest.
{
  echo "// AUTO-GENERATED by scripts/process-images.sh — do not edit by hand."
  echo "// Drop new images into content/images/ and re-run the script."
  echo "export const FINE_ART = ["
  printf '%b' "$entries"
  echo "];"
} > "$MANIFEST"

echo "Manifest written: $MANIFEST (${#sorted_masters[@]} image$([ ${#sorted_masters[@]} -eq 1 ] || echo s))"
